#!/usr/bin/env bash

## Description: Run project's Codesniffer inspections.
## Usage: cs
## Example: "ddev cs"

./vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,info --ignore=node_modules,bower_components,vendor ./web/modules/custom
exit_code1=$?

echo "Exit $((exit_code1))"
exit $((exit_code1))
