#!/usr/bin/env bash

## Description: Initialize a site.
## Usage: init-site
## Example: "ddev init-site"

# We disable email sending here so site-install does not return an error
# Credit: https://www.drupal.org/project/phpconfig/issues/1826652#comment-12071700
drush si -y standard --site-name="Drupal" install_configure_form.enable_update_status_emails=NULL
drush ev '\Drupal::entityTypeManager()->getStorage("shortcut_set")->load("default")->delete();'
drush cset system.site uuid "d7e28a68-fb1b-4494-bccf-c879207c3d3b" -y
drush cim -y
drush cr

# Run all the deploy hooks.
drush deploy

drush ev "node_access_rebuild();"
