#!/usr/bin/env bash

## Description: Initialize files
## Usage: init-files
## Example: "ddev init-files"

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# DDEV_APPROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
SITEDIR_PATH="${DDEV_DOCROOT}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${source} to ${dest}..."
	else
		echo "Overwriting ${source} to ${dest}..."
	fi
	cp $source $dest
}

copy_key_file()
{
  local source="$1"
  local dest_dir="/var/www/html/$2"
  local dest="${dest_dir}/$3"

  if [[ ! -d $dest_dir ]]; then
    mkdir $dest_dir
  fi

	if [[ ! -f $dest ]]; then
		echo "Copying ${source} to ${dest}..."
	else
		echo "Overwriting ${source} to ${dest}..."
	fi
  cp $source $dest
}
#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	copy_settings_file ".ddev/default_settings/settings.php" "${SITEDIR_PATH}/settings.php"
	copy_settings_file ".ddev/default_settings/settings.ddev.php" "${SITEDIR_PATH}/settings.ddev.php"
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
fix_permissions
init_settings
#-------------------------- END: Execution --------------------------------
